name: Deploy RAG Assistant to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ragassis
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4DD8D0EE57714AF980EFD952566BE3EE }}